#!/usr/bin/env bash

./aliases-setup.sh
./bash_prompt-setup.sh

echo "Updated .bashrc successfully."

# Now begins installing the packages

sudo apt install ninja-build gettext cmake unzip curl tmux gh

# Install neovim
git clone https://github.com/neovim/neovim
cd neovim && make CMAKE_BUILD_TYPE=Release
sudo make install

